name: Build actors latest versions
on:
  push:
    branches:
      - main
jobs:
  build-amazon-scraper:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./actor-amazon-scraper
    steps:
      # Install dependencies
      - uses: actions/checkout@v2
      - run: npm install
      # Build latest version
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.BUILD_ACTOR_URL }}
          webhook_secret: ${{ secrets.APIFY_TOKEN }}
